# System-wide .bashrc file for interactive bash(1) shells.

# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.

# Common aliases
alias l.='ls -d .* --color=auto'
alias ll='ls -lsh'
alias ls='ls --color=auto'
alias la='ll -a'
alias back='cd $OLDPWD'

PS1='[\u@\h \W] '
