#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     : Daniel Kesler <kesler.daniel@gmail.com>
# 
# Version     : 00.10
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

runlevel="firstboot"

if [ ! -d "${rc_base}/rc.${runlevel}.d" ]; then
	warning_msg "${rc_base}/rc.${runlevel}.d does not exist."
	exit 1
fi

for i in $(ls -v ${rc_base}/rc.${runlevel}.d/S* 2> /dev/null ); do
	${i} ${1}
done


