#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     :
# 
# Version     : 00.00
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

# Assure that the kernel has module support.
[ -e /proc/ksyms -o -e /proc/modules ] || exit 0

case "$1" in
  start)
 	#boot_msg "Loading modules."
	#
	#evaluate_retval
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?

