#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     : Daniel Kesler <kesler.daniel@gmail.com>
# 
# Version     : 00.01
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

case "$1" in
  start)	
	boot_msg "Mounting remaining file systems."
	if [ -x /etc/init.d/earlyboot.mount ]; then
		/etc/init.d/earlyboot.mount
	else
		mount -a -O no_netdev &> /dev/null
	fi
	evaluate_retval
	
	;;
  stop)
	boot_msg "Unmounting all other currently mounted file systems."
	if [ -x /etc/init.d/earlyboot.umount ]; then
		/etc/init.d/earlyboot.umount
	else
		umount -a -d -r &> /dev/null
	fi
	evaluate_retval
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

