#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     :
# 
# Version     : 00.00
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}
. /etc/default/modules

case "$1" in
	start)
		if [ "x$MODULES_PRINTK_LEVEL" != "x" ]; then
			dmesg -n "${MODULES_PRINTK_LEVEL}" 
		fi
	  
		boot_msg "Mounting /proc and /sys."

		mount -n /dev || failed=1
		mount -n /proc || failed=1
		mount -n /sys || failed=1
		
		(exit ${failed})
		evaluate_retval
		
		boot_msg "Remounting root file system in read-write mode."
		mount -n -o remount,rw / &> /dev/null
		evaluate_retval
		
		#rm -r /fastboot /forcefsck &> /dev/null
		
		boot_msg "Recording existing mounts in /etc/mtab."
		> /etc/mtab
		mount -n -f / || failed=1
		mount -f /proc || failed=1
		mount -f /sys || failed=1
		(exit ${failed})
		evaluate_retval
		;;
	stop)
		;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

