#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     : Daniel Kesler <kesler.daniel@gmail.com>
# 
# Version     : 00.01
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

case "$1" in
  start)
 	boot_msg "Remounting root file system in read-write mode."
	mount -n -o remount,rw / &> /dev/null
	evaluate_retval
	
	rm -r /fastboot /forcefsck &> /dev/null
	
	boot_msg "Recording existing mounts in /etc/mtab."
	> /etc/mtab
	mount -f / || failed=1
	mount -f /proc || failed=1
	mount -f /sys || failed=1
	(exit ${failed})
	evaluate_retval
	
	boot_msg "Mounting remaining file systems."
	mount -a -O no_netdev &> /dev/null
	evaluate_retval
	
	;;
  stop)
	boot_msg "Unmounting all other currently mounted file systems."
	umount -a -d -r &> /dev/null	
	evaluate_retval
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

