#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     : Daniel Kesler <kesler.daniel@gmail.com>
# 
# Version     : 00.10
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

case "$1" in
  start)
 	boot_msg "Starting network."
 	mkdir -p /run/network &> /dev/null
	/sbin/ifup -a > /dev/null 2>&1
	evaluate_retval
	
	;;
  stop)
	boot_msg "Stopping network."
	/sbin/ifdown -a > /dev/null 2>&1
	evaluate_retval
	;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
