################################################################################
#
# busybox
#
################################################################################

BUSYBOX_INITRAMFS_VERSION = 1.26.2
BUSYBOX_INITRAMFS_SITE = http://www.busybox.net/downloads
BUSYBOX_INITRAMFS_SOURCE = busybox-$(BUSYBOX_INITRAMFS_VERSION).tar.bz2
BUSYBOX_INITRAMFS_LICENSE = GPLv2
BUSYBOX_INITRAMFS_LICENSE_FILES = LICENSE

define BUSYBOX_INITRAMFS_APPLY_PATCHES
	if test -d package/busybox; then \
	  $(APPLY_PATCHES) $(@D) package/busybox \*.patch ; \
	fi;
endef

BUSYBOX_INITRAMFS_CFLAGS = \
	$(TARGET_CFLAGS)

BUSYBOX_INITRAMFS_LDFLAGS = \
	$(TARGET_LDFLAGS)


BUSYBOX_INITRAMFS_BUILD_CONFIG = $(BUSYBOX_INITRAMFS_DIR)/.config
# Allows the build system to tweak CFLAGS
BUSYBOX_INITRAMFS_MAKE_ENV = \
	$(TARGET_MAKE_ENV) \
	CFLAGS="$(BUSYBOX_INITRAMFS_CFLAGS)" \
	CFLAGS_busybox="$(BUSYBOX_INITRAMFS_CFLAGS_busybox)"
	
BUSYBOX_INITRAMFS_MAKE_OPTS = \
	CC="$(TARGET_CC)" \
	ARCH=$(KERNEL_ARCH) \
	PREFIX="$(BUSYBOX_INITRAMFS_TARGET_DIR)" \
	EXTRA_LDFLAGS="$(BUSYBOX_INITRAMFS_LDFLAGS)" \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	CONFIG_PREFIX="$(BUSYBOX_INITRAMFS_TARGET_DIR)" \
	SKIP_STRIP=y

BR2_PACKAGE_BUSYBOX_INITRAMFS_CONFIG = package/busybox-initramfs/busybox-initramfs.config

ifndef BUSYBOX_INITRAMFS_CONFIG_FILE
	BUSYBOX_INITRAMFS_CONFIG_FILE = $(call qstrip,$(BR2_PACKAGE_BUSYBOX_INITRAMFS_CONFIG))
endif

BUSYBOX_INITRAMFS_KCONFIG_FILE = $(BUSYBOX_INITRAMFS_CONFIG_FILE)
BUSYBOX_INITRAMFS_KCONFIG_EDITORS = menuconfig xconfig gconfig
BUSYBOX_INITRAMFS_KCONFIG_OPTS = $(BUSYBOX_INITRAMFS_MAKE_OPTS)

define BUSYBOX_INITRAMFS_FIX_SUID_PERMISSION
	$(BUSYBOX_INITRAMFS_FAKEROOT) chmod 4755 $(BUSYBOX_INITRAMFS_TARGET_DIR)/bin/busybox
endef

define BUSYBOX_INITRAMFS_INSTALL_TARGET_CMDS
	$(BUSYBOX_INITRAMFS_FAKEROOT) $(MAKE) $(BUSYBOX_INITRAMFS_MAKE_OPTS) -C $(@D) install
	$(BUSYBOX_INITRAMFS_FIX_SUID_PERMISSION)
endef


$(eval $(kconfig-package))
