#!/bin/sh
################################################################
# Begin $rc_base/init.d/
#
# Description : 
# 
# Authors     :
# 
# Version     : 00.00
#
# Notes       :
#
###############################################################

. /etc/default/rc
. ${rc_functions}

case "$1" in
  start)
    boot_msg "Starting mdev."
	echo /sbin/mdev >/proc/sys/kernel/hotplug
	/sbin/mdev -s
	evaluate_retval
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
